sudo: required
services:
    - docker
    
    
before_install:
    - docker build -f Dockerfile.dev -t marty11/docker-react .

script:
    - docker run -e CI=true marty11/docker-react npm run test
    